name: Deploy to PyPI


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip setuptools wheel
      - run: python setup.py sdist bdist_wheel
      - run: python -m twine check dist/*
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@v1
        with:
          username: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
