name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt-get update && apt-get upgrade
          apt-get install -y make
      - name: Build docs
        run: cd docs && make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
