name: Run tests and, if successful, deploy to PyPI


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - run: python -m pip install --upgrade pip setuptools wheel twine
      - run: python setup.py sdist bdist_wheel
      - run: python -m twine check dist/*
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Deploy
        if: github.event_name == 'push'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
